apiVersion: v1
kind: List
items:
  - apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - ldap:
          attributes:
            email:
            - mail
            id:
            - dn
            name:
            - cn
            preferredUsername:
            - "${vault:caas/data/sync-ldap@preferredUsername}"
          bindDN: ${git:LDAP_BIND_DN}
          bindPassword:
            name: ldap
          insecure: false
          url: ldaps://${git:LDAP_URL}:636/${git:LDAP_FILTER}
        mappingMethod: claim
        name: ldap
        type: LDAP
